name: Build Portfolio Theme

on:
  push:
    branches: [pleasetest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install
        
      - name: Add PostCSS to PATH
        run: export PATH="$PATH:node_modules/postcss"


      - name: Build
        working-directory: web/themes/custom/portfolio
        run: npm run build
